; Auto-generated. Do not edit!


(cl:in-package communication_pkg-msg)


;//! \htmlinclude PWMFeedback.msg.html

(cl:defclass <PWMFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass PWMFeedback (<PWMFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PWMFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PWMFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication_pkg-msg:<PWMFeedback> is deprecated: use communication_pkg-msg:PWMFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <PWMFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication_pkg-msg:feedback-val is deprecated.  Use communication_pkg-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PWMFeedback>) ostream)
  "Serializes a message object of type '<PWMFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'feedback)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PWMFeedback>) istream)
  "Deserializes a message object of type '<PWMFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PWMFeedback>)))
  "Returns string type for a message object of type '<PWMFeedback>"
  "communication_pkg/PWMFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PWMFeedback)))
  "Returns string type for a message object of type 'PWMFeedback"
  "communication_pkg/PWMFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PWMFeedback>)))
  "Returns md5sum for a message object of type '<PWMFeedback>"
  "cbfbf3355c876d056ca78e89534a5173")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PWMFeedback)))
  "Returns md5sum for a message object of type 'PWMFeedback"
  "cbfbf3355c876d056ca78e89534a5173")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PWMFeedback>)))
  "Returns full string definition for message of type '<PWMFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint32 feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PWMFeedback)))
  "Returns full string definition for message of type 'PWMFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint32 feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PWMFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PWMFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PWMFeedback
    (cl:cons ':feedback (feedback msg))
))
