; Auto-generated. Do not edit!


(cl:in-package communication_pkg-msg)


;//! \htmlinclude PWMGoal.msg.html

(cl:defclass <PWMGoal> (roslisp-msg-protocol:ros-message)
  ((pwm
    :reader pwm
    :initarg :pwm
    :type (cl:vector cl:integer)
   :initform (cl:make-array 12 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass PWMGoal (<PWMGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PWMGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PWMGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication_pkg-msg:<PWMGoal> is deprecated: use communication_pkg-msg:PWMGoal instead.")))

(cl:ensure-generic-function 'pwm-val :lambda-list '(m))
(cl:defmethod pwm-val ((m <PWMGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication_pkg-msg:pwm-val is deprecated.  Use communication_pkg-msg:pwm instead.")
  (pwm m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PWMGoal>) ostream)
  "Serializes a message object of type '<PWMGoal>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'pwm))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PWMGoal>) istream)
  "Deserializes a message object of type '<PWMGoal>"
  (cl:setf (cl:slot-value msg 'pwm) (cl:make-array 12))
  (cl:let ((vals (cl:slot-value msg 'pwm)))
    (cl:dotimes (i 12)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PWMGoal>)))
  "Returns string type for a message object of type '<PWMGoal>"
  "communication_pkg/PWMGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PWMGoal)))
  "Returns string type for a message object of type 'PWMGoal"
  "communication_pkg/PWMGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PWMGoal>)))
  "Returns md5sum for a message object of type '<PWMGoal>"
  "d0c4011a7c89424eda9fa1046fc1e8b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PWMGoal)))
  "Returns md5sum for a message object of type 'PWMGoal"
  "d0c4011a7c89424eda9fa1046fc1e8b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PWMGoal>)))
  "Returns full string definition for message of type '<PWMGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#goal definition~%char[12] pwm~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PWMGoal)))
  "Returns full string definition for message of type 'PWMGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#goal definition~%char[12] pwm~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PWMGoal>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pwm) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PWMGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PWMGoal
    (cl:cons ':pwm (pwm msg))
))
