; Auto-generated. Do not edit!


(cl:in-package communication_pkg-msg)


;//! \htmlinclude PWMResult.msg.html

(cl:defclass <PWMResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass PWMResult (<PWMResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PWMResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PWMResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication_pkg-msg:<PWMResult> is deprecated: use communication_pkg-msg:PWMResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <PWMResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication_pkg-msg:result-val is deprecated.  Use communication_pkg-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PWMResult>) ostream)
  "Serializes a message object of type '<PWMResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PWMResult>) istream)
  "Deserializes a message object of type '<PWMResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PWMResult>)))
  "Returns string type for a message object of type '<PWMResult>"
  "communication_pkg/PWMResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PWMResult)))
  "Returns string type for a message object of type 'PWMResult"
  "communication_pkg/PWMResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PWMResult>)))
  "Returns md5sum for a message object of type '<PWMResult>"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PWMResult)))
  "Returns md5sum for a message object of type 'PWMResult"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PWMResult>)))
  "Returns full string definition for message of type '<PWMResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PWMResult)))
  "Returns full string definition for message of type 'PWMResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PWMResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PWMResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PWMResult
    (cl:cons ':result (result msg))
))
