// Generated by gencpp from file communication_pkg/PWMGoal.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_PKG_MESSAGE_PWMGOAL_H
#define COMMUNICATION_PKG_MESSAGE_PWMGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_pkg
{
template <class ContainerAllocator>
struct PWMGoal_
{
  typedef PWMGoal_<ContainerAllocator> Type;

  PWMGoal_()
    : pwm()  {
      pwm.assign(0);
  }
  PWMGoal_(const ContainerAllocator& _alloc)
    : pwm()  {
      pwm.assign(0);
  }



   typedef boost::array<uint8_t, 12>  _pwm_type;
  _pwm_type pwm;




  typedef boost::shared_ptr< ::communication_pkg::PWMGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_pkg::PWMGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PWMGoal_

typedef ::communication_pkg::PWMGoal_<std::allocator<void> > PWMGoal;

typedef boost::shared_ptr< ::communication_pkg::PWMGoal > PWMGoalPtr;
typedef boost::shared_ptr< ::communication_pkg::PWMGoal const> PWMGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_pkg::PWMGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_pkg::PWMGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace communication_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'communication_pkg': ['/home/sxubach/Documents/Robot_Learning/robotLearning/catkin_ws/devel/share/communication_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::communication_pkg::PWMGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_pkg::PWMGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_pkg::PWMGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_pkg::PWMGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_pkg::PWMGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_pkg::PWMGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_pkg::PWMGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0c4011a7c89424eda9fa1046fc1e8b5";
  }

  static const char* value(const ::communication_pkg::PWMGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0c4011a7c89424eULL;
  static const uint64_t static_value2 = 0xda9fa1046fc1e8b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_pkg::PWMGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_pkg/PWMGoal";
  }

  static const char* value(const ::communication_pkg::PWMGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_pkg::PWMGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
#goal definition\n\
char[12] pwm\n\
";
  }

  static const char* value(const ::communication_pkg::PWMGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_pkg::PWMGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PWMGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_pkg::PWMGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_pkg::PWMGoal_<ContainerAllocator>& v)
  {
    s << indent << "pwm[]" << std::endl;
    for (size_t i = 0; i < v.pwm.size(); ++i)
    {
      s << indent << "  pwm[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.pwm[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_PKG_MESSAGE_PWMGOAL_H
