// Generated by gencpp from file communication_pkg/PWMResult.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_PKG_MESSAGE_PWMRESULT_H
#define COMMUNICATION_PKG_MESSAGE_PWMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_pkg
{
template <class ContainerAllocator>
struct PWMResult_
{
  typedef PWMResult_<ContainerAllocator> Type;

  PWMResult_()
    : result(0)  {
    }
  PWMResult_(const ContainerAllocator& _alloc)
    : result(0)  {
    }



   typedef uint32_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::communication_pkg::PWMResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_pkg::PWMResult_<ContainerAllocator> const> ConstPtr;

}; // struct PWMResult_

typedef ::communication_pkg::PWMResult_<std::allocator<void> > PWMResult;

typedef boost::shared_ptr< ::communication_pkg::PWMResult > PWMResultPtr;
typedef boost::shared_ptr< ::communication_pkg::PWMResult const> PWMResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_pkg::PWMResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_pkg::PWMResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace communication_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'communication_pkg': ['/home/sxubach/Documents/Robot_Learning/robotLearning/catkin_ws/devel/share/communication_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::communication_pkg::PWMResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_pkg::PWMResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_pkg::PWMResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_pkg::PWMResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_pkg::PWMResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_pkg::PWMResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_pkg::PWMResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13d5d28ceaaadbc975dd072a2e10b88a";
  }

  static const char* value(const ::communication_pkg::PWMResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13d5d28ceaaadbc9ULL;
  static const uint64_t static_value2 = 0x75dd072a2e10b88aULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_pkg::PWMResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_pkg/PWMResult";
  }

  static const char* value(const ::communication_pkg::PWMResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_pkg::PWMResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
uint32 result\n\
";
  }

  static const char* value(const ::communication_pkg::PWMResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_pkg::PWMResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PWMResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_pkg::PWMResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_pkg::PWMResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_PKG_MESSAGE_PWMRESULT_H
